### ISSUE TITLE
SB List Command Prints Newer Roles with Asterisk(*)

### ISSUE THREAD

**Issue by ekk88d** [saltyorg/sb#14]
Since the dev's have been great about adding so many roles in the `sb list` command, it's useful for a marker to indicate new roles e.g. `dozzle*` or `*dozzle`

**Comment by saltydk** [comment]
Firstly, thanks for submitting a feature request.

While that might sound easy to add this it is not, what if someone updates after a year, how do we determine what was new since he/she updated or did a restore? It is non-trivial when we don't track what version of Saltbox was used previously etc.

Unless you intend to make a PR with this feature it will be ignored as I am sadly not personally interested in exploring such a feature.

So I will close this issue as it doesn't fit the goals of the tool, in my opinion, which is to install stuff, not being a changelog especially given that Saltbox will likely never have one either outside of a massive rewrite.

Apologies for the blunt answer.
